const translations = {
    en: {
        "nav-home": "Home",
        "nav-menu": "Menu",
        "nav-about": "About",
        "nav-contact": "Contact",
        "hero-title": "A Taste of Pure Condensed Matter",
        "hero-subtitle": "Maximizing fluffiness through oxide thin film theories.",
        "hero-cta": "View the Standard Model",
        "intro-title": "Why Cloud Fluff9?",
        "intro-1-title": "Physics-Based Fluff",
        "intro-1-desc": "Our recipes are calculated to the molecular level for optimal structural integrity.",
        "intro-2-title": "Dorm 9 Exclusive",
        "intro-2-desc": "Located in the legendary Kitchen of Dormitory 9.",
        "intro-3-title": "Chef's Expertise",
        "intro-3-desc": "Cooked by a PhD candidate (when not writing papers).",
        "menu-title": "The Menu",
        "menu-item-title": "The Standard Model Souffle",
        "menu-item-desc": "A perfectly symmetric composition of egg whites and sugar, stabilized by van der Waals forces. Served with a quantum superposition of butter and syrup.",
        "menu-item-price": "₩ 120,000",
        "about-title": "About the Chef",
        "about-chef-name": "Chef 'Doctor' Lee",
        "about-chef-role": "PhD Candidate, Condensed Matter Physics",
        "about-chef-bio": "Specializing in Oxide Thin Films, Chef Lee realized that the same principles of epitaxial growth could be applied to souffle pancakes to achieve maximum fluffiness. Currently balancing lab hours with whisking hours.",
        "about-asst-title": "Assistant Chefs",
        "about-asst-1": "Assistant 1: The Master's Student (Forced Labor)",
        "about-asst-2": "Assistant 2: The Undergrad (Just happy to be here)",
        "contact-title": "Visit Us",
        "contact-address": "Building 9 Kitchen, University Dormitories",
        "contact-open": "Open: Whenever the Chef is not in the lab.",
        "contact-btn": "Make a Reservation"
    },
    kr: {
        "nav-home": "홈",
        "nav-menu": "메뉴",
        "nav-about": "소개",
        "nav-contact": "문의",
        "hero-title": "응집물질의 맛",
        "hero-subtitle": "산화물 박막 이론으로 극대화된 폭신함을 경험하세요.",
        "hero-cta": "표준 모형 보기",
        "intro-title": "왜 Cloud Fluff9인가?",
        "intro-1-title": "물리학 기반 폭신함",
        "intro-1-desc": "분자 수준까지 계산된 레시피로 최적의 구조적 안정성을 자랑합니다.",
        "intro-2-title": "9동 기숙사 전용",
        "intro-2-desc": "전설적인 9동 기숙사 주방에서 탄생했습니다.",
        "intro-3-title": "박사과정의 손맛",
        "intro-3-desc": "논문 쓰다 지친 박사과정생이 직접 구워드립니다.",
        "menu-title": "메뉴",
        "menu-item-title": "표준 모형 수플레 (Standard Model)",
        "menu-item-desc": "반데르발스 힘으로 안정화된 계란 흰자와 설탕의 완벽한 대칭. 버터와 시럽의 양자 중첩 상태로 제공됩니다.",
        "menu-item-price": "₩ 120,000",
        "about-title": "쉐프 소개",
        "about-chef-name": "이박사 (가칭)",
        "about-chef-role": "응집물질물리 박사과정",
        "about-chef-bio": "산화물 박막 전공. 에피택시 성장 원리를 수플레 팬케이크에 적용하여 극한의 부드러움을 실현했습니다. 현재 랩실과 주방을 오가며 이중생활 중입니다.",
        "about-asst-title": "보조 쉐프",
        "about-asst-1": "보조 1: 석사과정 (강제 동원됨)",
        "about-asst-2": "보조 2: 학부생 (그저 행복함)",
        "contact-title": "오시는 길",
        "contact-address": "대학교 기숙사 9동 주방",
        "contact-open": "영업 시간: 쉐프가 랩실에 없을 때",
        "contact-btn": "예약하기"
    }
};
